### PR TITLE
optimized memory allocation in one-hot-encoding

### PR DESCRIPTION
**Pull request by pkorshunov**
If the audio files are larger than an hour, the on_hot_encoding matrix can become extremely large if not optimized.

### CODE REVIEW

**Comment by pkorshunov** [comment]
Actually, I would rather use -1 values for `unknown` timestamps instead of the current `np.NAN`, because `np.NAN` is `float64` which occupies a lot of memory. But if we used negative values like -1 instead, the whole matrix can be of time `int8` or `int16` and this can save a lot of memory and speed things up as well.

**Comment by pkorshunov** [comment]
But I didn't changed np.NAN to -1 because I was not sure how this `one_hot_encoded` matrix is used in other parts of pyannote, so I didn't want to mess it up.

**Comment by pkorshunov** [comment]
In any case, at least the current fix allowed me to start training SAD on a set of databases including LibriSpeech and others with long audio files.

**Comment by hbredin** [comment]
Awesome. 

Let me check exactly where `one_hot_encoding` but I guess we can modify these other places to expect -1 instead of NaN.

**Comment by hbredin** [comment]
Would https://docs.scipy.org/doc/scipy/reference/sparse.html be an even better option?

**Comment by pkorshunov** [comment]
it could be better, yes. I'll look into it tomorrow.

**Comment by hbredin** [comment]
Just had a closer look at how the output of `one_hot_encoding` is currently used in `pyannote.audio`([here](https://github.com/pyannote/pyannote-audio/blob/0731ccd2b9ab6d81fcbc6e0a73831c264243e7ec/pyannote/audio/labeling/tasks/speech_activity_detection.py#L101-L102) and [here](https://github.com/pyannote/pyannote-audio/blob/0731ccd2b9ab6d81fcbc6e0a73831c264243e7ec/pyannote/audio/labeling/tasks/speaker_change_detection.py#L121-L122))

It looks like using -1 is OK because we are [not](https://github.com/pyannote/pyannote-audio/blob/0731ccd2b9ab6d81fcbc6e0a73831c264243e7ec/pyannote/audio/labeling/tasks/base.py#L137-L138) iterating over the un-annotated regions anyway... So, using `-1` and `int8` data type seems fine. A compromise might be to add an extra parameter to `one_hot_encoding` to let the user decide which value to use (-1 or NaN).

If sparse arrays are efficient (i.e. not slower than regular numpy arrays for indexing), they could be even better...

**Comment by pkorshunov** [comment]
Ok, that's good that -1 can be used. It will simplify this array a lot. But I wonder why would the user care about the NAN values?

**Comment by hbredin** [comment]
You are right. We can stick to -1.

The only problem I see with -1 is if we choose to switch to sparse arrays: large un-annotated regions will be marked as -1 and therefore we loose the advantage of sparse arrays...

**Pull request merged**
