### PR TITLE
Fix documentation of Timeline.__bool__

### PR DESCRIPTION
**Pull request by ronshapiro**

### CODE REVIEW

**Comment by hbredin** [comment]
Good catch, thanks! 
While you are at it, would you mind fixing `Annotation.__bool__` as well? :-)

**Comment by ronshapiro** [comment]
Good point! Done

**Review by hbredin — APPROVED** [review]

**Comment by hbredin** [comment]
Thanks a lot for your contribution! This will be part of next release.

Out of curiosity, may I ask what you are using `pyannote.core` for?

**Comment by ronshapiro** [comment]
I come from the Java world, where Guava's [`RangeMap`](https://guava.dev/releases/31.0.1-jre/api/docs/com/google/common/collect/RangeMap.html)/`RangeSet` is a core building block of lots of code. `Annotation`/`Timeline`/`Segment` cover that functionality pretty well!

**Pull request merged**
